RentalKendaraan_093/Controllers/PeminjamenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RentalKendaraan_093.Models;

namespace RentalKendaraan_093.Controllers
{
    public class PeminjamenController : Controller
    {
        private readonly RentKendaraanContext _context;

        public PeminjamenController(RentKendaraanContext context)
        {
            _context = context;
        }

        // GET: Peminjamen
        public async Task<IActionResult> Index(string ktsd, string searchString, string sortOrder, string currentFilter, int? pageNumber)
        {
            //buat list penyimpanan ketersediaan
            var ktsdList = new List<string>();

            //query mengambil data
            var ktsQuery = from d in _context.Peminjaman orderby d.IdKendaraanNavigation.NamaKendaraan.ToString() select d.IdKendaraanNavigation.NamaKendaraan;

            ktsdList.AddRange(ktsQuery.Distinct());

            //untuk menampilkan di view
            ViewBag.ktsd = new SelectList(ktsdList);

            //panggil db context
            var menu = from m in _context.Peminjaman.Include(p => p.IdCustomerNavigation).Include(p => p.IdJaminanNavigation).Include(p => p.IdKendaraanNavigation) select m;

            //untuk memilih dropdownlist ketersediaan
            if (!string.IsNullOrEmpty(ktsd))
            {
                menu = menu.Where(x => x.IdKendaraanNavigation.NamaKendaraan.ToString() == ktsd);
            }

            //untuk search data
            if (!string.IsNullOrEmpty(searchString))
            {
                menu = menu.Where(s => s.Biaya.ToString().Contains(searchString) || s.IdCustomerNavigation.NamaCustomer.Contains(searchString) || s.IdJaminanNavigation.NamaJaminan.Contains(searchString) || s.IdKendaraanNavigation.NamaKendaraan.Contains(searchString));
            }

            //untuk sorting
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";

            switch (sortOrder)
            {
                case "name_desc":
                    menu = menu.OrderByDescending(s => s.IdCustomerNavigation.NamaCustomer);
                    break;
                case "Date":
                    menu = menu.OrderBy(s => s.TglPeminjaman);
                    break;
                case "date_desc":
                    menu = menu.OrderByDescending(s => s.TglPeminjaman);
                    break;
                default: //name ascending
                    menu = menu.OrderBy(s => s.IdCustomerNavigation.NamaCustomer);
                    break;
            }

            //membuat pagedList
            ViewData["CurrentSort"] = sortOrder;

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            //Definisi jumlah data pada halaman
            int pageSize = 5;

            return View(await PaginatedList<Peminjaman>.CreateAsync(menu.AsNoTracking(), pageNumber ?? 1, pageSize));
            //var rentKendaraanContext = _context.Peminjaman.Include(p => p.IdCustomerNavigation).Include(p => p.IdJaminanNavigation).Include(p => p.IdKendaraanNavigation);
            //return View(await rentKendaraanContext.ToListAsync());
        }

    // GET: Peminjamen/Details/5
    public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var peminjaman = await _context.Peminjaman
                .Include(p => p.IdCustomerNavigation)
                .Include(p => p.IdJaminanNavigation)
                .Include(p => p.IdKendaraanNavigation)
                .FirstOrDefaultAsync(m => m.IdPeminjaman == id);
            if (peminjaman == null)
            {
                return NotFound();
            }

            return View(peminjaman);
        }

        // GET: Peminjamen/Create
        public IActionResult Create()
        {
            ViewData["IdCustomer"] = new SelectList(_context.Customer, "IdCustomer", "NamaCustomer");
            ViewData["IdJaminan"] = new SelectList(_context.Jaminan, "IdJaminan", "NamaJaminan");
            ViewData["IdKendaraan"] = new SelectList(_context.Kendaraan, "IdKendaraan", "NamaKendaraan");
            return View();
        }

        // POST: Peminjamen/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdPeminjaman,TglPeminjaman,IdKendaraan,IdCustomer,IdJaminan,Biaya")] Peminjaman peminjaman)
        {
            if (ModelState.IsValid)
            {
                _context.Add(peminjaman);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdCustomer"] = new SelectList(_context.Customer, "IdCustomer", "NamaCustomer", peminjaman.IdCustomer);
            ViewData["IdJaminan"] = new SelectList(_context.Jaminan, "IdJaminan", "NamaJaminan", peminjaman.IdJaminan);
            ViewData["IdKendaraan"] = new SelectList(_context.Kendaraan, "IdKendaraan", "NamaKendaraan", peminjaman.IdKendaraan);
            return View(peminjaman);
        }

        // GET: Peminjamen/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var peminjaman = await _context.Peminjaman.FindAsync(id);
            if (peminjaman == null)
            {
                return NotFound();
            }
            ViewData["IdCustomer"] = new SelectList(_context.Customer, "IdCustomer", "NamaCustomer", peminjaman.IdCustomer);
            ViewData["IdJaminan"] = new SelectList(_context.Jaminan, "IdJaminan", "NamaJaminan", peminjaman.IdJaminan);
            ViewData["IdKendaraan"] = new SelectList(_context.Kendaraan, "IdKendaraan", "NamaKendaraan", peminjaman.IdKendaraan);
            return View(peminjaman);
        }

        // POST: Peminjamen/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdPeminjaman,TglPeminjaman,IdKendaraan,IdCustomer,IdJaminan,Biaya")] Peminjaman peminjaman)
        {
            if (id != peminjaman.IdPeminjaman)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(peminjaman);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PeminjamanExists(peminjaman.IdPeminjaman))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdCustomer"] = new SelectList(_context.Customer, "IdCustomer", "NamaCustomer", peminjaman.IdCustomer);
            ViewData["IdJaminan"] = new SelectList(_context.Jaminan, "IdJaminan", "NamaJaminan", peminjaman.IdJaminan);
            ViewData["IdKendaraan"] = new SelectList(_context.Kendaraan, "IdKendaraan", "NamaKendaraan", peminjaman.IdKendaraan);
            return View(peminjaman);
        }

        // GET: Peminjamen/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var peminjaman = await _context.Peminjaman
                .Include(p => p.IdCustomerNavigation)
                .Include(p => p.IdJaminanNavigation)
                .Include(p => p.IdKendaraanNavigation)
                .FirstOrDefaultAsync(m => m.IdPeminjaman == id);
            if (peminjaman == null)
            {
                return NotFound();
            }

            return View(peminjaman);
        }

        // POST: Peminjamen/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var peminjaman = await _context.Peminjaman.FindAsync(id);
            _context.Peminjaman.Remove(peminjaman);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PeminjamanExists(int id)
        {
            return _context.Peminjaman.Any(e => e.IdPeminjaman == id);
        }
    }
}

RentalKendaraan_093/Views/Peminjamen/Create.cshtml
@model RentalKendaraan_093.Models.Peminjaman

@{
    ViewData["Title"] = "Create";
}

<h2>Tambah Data</h2>

<h4>Peminjaman</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TglPeminjaman" class="control-label"></label>
                <input asp-for="TglPeminjaman" class="form-control" />
                <span asp-validation-for="TglPeminjaman" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdKendaraan" class="control-label"></label>
                <select asp-for="IdKendaraan" class ="form-control" asp-items="ViewBag.IdKendaraan"></select>
            </div>
            <div class="form-group">
                <label asp-for="IdCustomer" class="control-label"></label>
                <select asp-for="IdCustomer" class ="form-control" asp-items="ViewBag.IdCustomer"></select>
            </div>
            <div class="form-group">
                <label asp-for="IdJaminan" class="control-label"></label>
                <select asp-for="IdJaminan" class ="form-control" asp-items="ViewBag.IdJaminan"></select>
            </div>
            <div class="form-group">
                <label asp-for="Biaya" class="control-label"></label>
                <input asp-for="Biaya" class="form-control" />
                <span asp-validation-for="Biaya" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Simpan" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Kembali</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RentalKendaraan_093/Views/Peminjamen/Delete.cshtml
@model RentalKendaraan_093.Models.Peminjaman

@{
    ViewData["Title"] = "Delete";
}

<h2>Hapus Data Peminjaman</h2>

<h3>Apakah anda yakin ingin menghapus data ini?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TglPeminjaman)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TglPeminjaman)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Biaya)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Biaya)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdCustomer)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdCustomer)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdJaminan)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdJaminan)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdKendaraan)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdKendaraan)
        </dd>



    </dl>
</div>
<div>
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdPeminjaman" />
        <input type="submit" value="Hapus" class="btn btn-default" /> |
        <a asp-action="Index">Kembali</a>
    </form>
</div>

RentalKendaraan_093/Views/Peminjamen/Details.cshtml
@model RentalKendaraan_093.Models.Peminjaman

@{
    ViewData["Title"] = "Details";
}

<h2>Detail Data</h2>

<div>
    <h4>Peminjaman</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TglPeminjaman)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TglPeminjaman)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Biaya)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Biaya)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdCustomerNavigation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdCustomerNavigation.IdCustomer)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdJaminanNavigation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdJaminanNavigation.IdJaminan)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdKendaraanNavigation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdKendaraanNavigation.IdKendaraan)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.IdPeminjaman">Udah</a> |
    <a asp-action="Index">Kembali</a>
</div>

RentalKendaraan_093/Views/Peminjamen/Edit.cshtml
@model RentalKendaraan_093.Models.Peminjaman

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Peminjaman</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdPeminjaman" />
            <div class="form-group">
                <label asp-for="TglPeminjaman" class="control-label"></label>
                <input asp-for="TglPeminjaman" class="form-control" />
                <span asp-validation-for="TglPeminjaman" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdKendaraan" class="control-label"></label>
                <select asp-for="IdKendaraan" class="form-control" asp-items="ViewBag.IdKendaraan"></select>
                <span asp-validation-for="IdKendaraan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdCustomer" class="control-label"></label>
                <select asp-for="IdCustomer" class="form-control" asp-items="ViewBag.IdCustomer"></select>
                <span asp-validation-for="IdCustomer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdJaminan" class="control-label"></label>
                <select asp-for="IdJaminan" class="form-control" asp-items="ViewBag.IdJaminan"></select>
                <span asp-validation-for="IdJaminan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Biaya" class="control-label"></label>
                <input asp-for="Biaya" class="form-control" />
                <span asp-validation-for="Biaya" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Simpan" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Kembali</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RentalKendaraan_093/Views/Peminjamen/Index.cshtml
@model PaginatedList<RentalKendaraan_093.Models.Peminjaman>

@{
    ViewData["Title"] = "Index";
}

<h2>Peminjaman</h2>

<p>
    <a asp-action="Create">Tambah Data Baru</a>
</p>

@using (Html.BeginForm("Index", "Peminjamen", FormMethod.Get))
{
    <p>
        Tipe jaminan: @Html.DropDownList("ktsd", "Pilih Kendaraan")
        Cari Data : @Html.TextBox("searchString")
        <input type="submit" value="Filter" />
    </p>
}

<table class="table">
    <thead>
        <tr>
            <th>
                @*Html.DisplayNameFor(model => model.TglPeminjaman)*@
                <a asp-action="Index" asp-route-sortOrder="@ViewData["DateSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Tanggal Peminjaman</a>
            </th>
            <th>
                @*Html.DisplayNameFor(model => model.IdCustomerNavigation.NamaCustomer)*@
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Nama Customer</a>
            </th>
            <th>
                @*Html.DisplayNameFor(model => model.Biaya)*@
                @Html.DisplayName("Biaya")
            </th>
            <th>
                @*Html.DisplayNameFor(model => model.IdJaminanNavigation.NamaJaminan)*@
                @Html.DisplayName("Jaminan")
            </th>
            <th>
                @*Html.DisplayNameFor(model => model.IdKendaraanNavigation.NamaKendaraan)*@
                @Html.DisplayName("Nama Kendaraan")
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.TglPeminjaman)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdCustomerNavigation.NamaCustomer)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Biaya)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdJaminanNavigation.NamaJaminan)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdKendaraanNavigation.NamaKendaraan)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.IdPeminjaman"><i class="fa fa-marker fa-lg"></i></a> |
                    <a asp-action="Details" asp-route-id="@item.IdPeminjaman"><i class="fa fa-list fa-lg"></i></a> |
                    <a asp-action="Delete" asp-route-id="@item.IdPeminjaman"><i class="fa fa-trash-alt fa-lg"></i></a>
                    <!--<a asp-action="Edit" asp-route-id="@item.IdPeminjaman">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.IdPeminjaman">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.IdPeminjaman">Delete</a>-->
                </td>
            </tr>
        }
    </tbody>
</table>
@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "enabled" : "";
}

<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   asp-route-currentfilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled">
    Previous
</a>

<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   asp-route-currentfilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled">
    Next
</a>